import styles from './TermsModal.module.css';

type TermsModalProps = {
    isOpen: boolean;
    onClose: () => void;
    onConfirm: () => void;
    isSubmitting: boolean;
};

const TermsModal = ({ isOpen, onClose, onConfirm, isSubmitting }: TermsModalProps) => {
    if (!isOpen) return null;

    return (
        <div className={styles['modal-overlay']} onClick={onClose}>
            <div className={styles['modal-content']} onClick={(e) => e.stopPropagation()}>
                <h2 className={styles['modal-header']}>🎨 Artwork Submission – Terms & Conditions</h2>
                <div className={styles['terms-container']}>
                    <h3>Organized by Daami Event</h3>
                    <p>By submitting your artwork to Daami Event, you acknowledge and agree to abide by the following terms and conditions. These rules are designed to ensure fairness, creativity, and legal clarity for all participants.</p>

                    <h3>🔒 1. Originality & Ownership</h3>
                    <p>All submitted artwork must be 100% original and created solely by the participant.</p>
                    <p>Submissions must not be copied, traced, or heavily inspired from any existing artwork, online or offline.</p>
                    <p>Any use of copyrighted materials, stock graphics, or plagiarized designs is strictly prohibited and will result in immediate disqualification.</p>
                    <p>If AI tools are used (e.g., Midjourney, DALL·E, etc.), the input prompts must be written by the participant and the final result must be significantly curated or modified by them.</p>

                    <h3>🎯 2. Theme Adherence</h3>
                    <p>All artwork must strictly follow the theme provided by Daami Event.</p>
                    <p>Off-theme submissions will be rejected without notice.</p>
                    <p>Participants are encouraged to explore the theme creatively, but the central concept must remain intact and relevant.</p>
                    
                    <h3>🚫 3. Prohibited Content</h3>
                    <p>Artwork must not include or promote: Vulgarity, explicit nudity, sexual content, or adult themes; Hate speech, racism, violence, or offensive symbols; Religious or political propaganda.</p>
                    <p>Daami Event retains the right to reject any submission deemed inappropriate or misaligned with the event's values.</p>

                    <h3>⚖️ 4. Intellectual Property Rights</h3>
                    <p>The artist retains moral rights to their work, including attribution.</p>
                    <p>However, by submitting the artwork, the participant grants Daami Event: A non-exclusive, royalty-free, worldwide license to use, display, promote, and share the artwork across all media platforms, both online and offline; The right to feature the work in exhibitions, merchandise, social media, and promotional materials; The right to sell the artwork or reproductions under Daami Event’s branding (credit will be provided to the creator wherever applicable).</p>
                    <p>Participants will not be compensated for the above usage unless explicitly agreed upon in a separate licensing agreement.</p>

                    <h3>🛡️ 5. Verification & Plagiarism Monitoring</h3>
                    <p>All entries are subject to AI plagiarism detection tools and manual review.</p>
                    <p>If a submission is found to be generated by AI without creative input, or traced/copied from another source, it will be automatically disqualified.</p>
                    <p>Repeat offenders may be banned from future Daami Event contests.</p>

                    <h3>📅 6. Submission Format & Deadlines</h3>
                    <p>All artworks must be submitted in the specified format (JPEG, PNG, or PDF) within the given deadline.</p>
                    <p>Late submissions will not be considered unless prior written permission is obtained.</p>
                    <p>Each participant is allowed to submit one final entry only, unless otherwise specified.</p>
                    
                    <h3>👥 7. Eligibility</h3>
                    <p>Open to individuals aged 13 and above.</p>
                    <p>Participants under 18 must have parental or guardian consent to participate.</p>
                    <p>Daami Event reserves the right to verify the identity and eligibility of participants.</p>

                    <h3>📝 8. Acceptance of Terms</h3>
                    <p>By submitting your artwork, you confirm that you have read, understood, and agreed to all the terms and conditions.</p>
                    <p>Daami Event holds the final decision-making authority in all matters regarding the contest or usage of submitted works.</p>

                </div>
                <div className={styles['modal-actions']}>
                    <button onClick={onClose} className={`${styles['action-button']} ${styles['cancel-button']}`}>
                        Cancel
                    </button>
                    <button onClick={onConfirm} disabled={isSubmitting} className={`${styles['action-button']} ${styles['submit-button']}`}>
                        {isSubmitting ? 'Submitting...' : 'I Agree & Submit'}
                    </button>
                </div>
            </div>
        </div>
    );
};

export default TermsModal; 